### ISSUE TITLE
Error in category edit page after install

### ISSUE THREAD

**Issue by danielchicote** [firegento/firegento-dynamiccategory#68]
> Element with id "conditions__1__type" already exists

Trace:
#0 \lib\Varien\Data\Form.php(107): Varien_Data_Form->checkElementId('conditions__1__...')
#1 \lib\Varien\Data\Form\Abstract.php(148): Varien_Data_Form->addElement(Object(Varien_Data_Form_Element_Hidden), false)
#2 \app\code\core\Mage\Rule\Model\Condition\Abstract.php(406): Varien_Data_Form_Abstract->addField('conditions__1__...', 'hidden', Array)
#3 \app\code\core\Mage\Rule\Model\Condition\Combine.php(255): Mage_Rule_Model_Condition_Abstract->getTypeElement()
#4 \app\code\core\Mage\Rule\Model\Condition\Combine.php(274): Mage_Rule_Model_Condition_Combine->asHtml()
#5 \app\code\community\FireGento\DynamicCategory\Block\Conditions.php(41): Mage_Rule_Model_Condition_Combine->asHtmlRecursive()
#6 \lib\Varien\Data\Form\Element\Abstract.php(223): FireGento_DynamicCategory_Block_Conditions->render(Object(Varien_Data_Form_Element_Text))
#7 \lib\Varien\Data\Form\Element\Text.php(46): Varien_Data_Form_Element_Abstract->getHtml()
#8 \lib\Varien\Data\Form\Element\Abstract.php(233): Varien_Data_Form_Element_Text->getHtml()
#9 \lib\Varien\Data\Form\Element\Fieldset.php(90): Varien_Data_Form_Element_Abstract->toHtml()
#10 \app\design\adminhtml\default\default\template\dynamiccategory\fieldset.phtml(35): Varien_Data_Form_Element_Fieldset->getChildrenHtml()
#11 \app\code\local\Mage\Core\Block\Template.php(241): include('C:\\xampp\\htdocs...')
#12 \app\code\local\Mage\Core\Block\Template.php(273): Mage_Core_Block_Template->fetchView('adminhtml\\defau...')
#13 \app\code\local\Mage\Core\Block\Template.php(287): Mage_Core_Block_Template->renderView()
#14 \app\code\core\Mage\Adminhtml\Block\Template.php(81): Mage_Core_Block_Template->_toHtml()
#15 \app\code\core\Mage\Core\Block\Abstract.php(919): Mage_Adminhtml_Block_Template->_toHtml()
#16 \app\code\core\Mage\Adminhtml\Block\Widget\Form\Renderer\Fieldset.php(51): Mage_Core_Block_Abstract->toHtml()
#17 \lib\Varien\Data\Form\Element\Abstract.php(223): Mage_Adminhtml_Block_Widget_Form_Renderer_Fieldset->render(Object(Varien_Data_Form_Element_Fieldset))
#18 \lib\Varien\Data\Form\Element\Abstract.php(233): Varien_Data_Form_Element_Abstract->getHtml()
#19 \lib\Varien\Data\Form.php(244): Varien_Data_Form_Element_Abstract->toHtml()
#20 \lib\Varien\Data\Form.php(256): Varien_Data_Form->toHtml()
#21 \app\code\core\Mage\Adminhtml\Block\Widget\Form.php(108): Varien_Data_Form->getHtml()
#22 \app\design\adminhtml\default\default\template\widget\form.phtml(28): Mage_Adminhtml_Block_Widget_Form->getFormHtml()
#23 \app\code\local\Mage\Core\Block\Template.php(241): include('C:\\xampp\\htdocs...')
#24 \app\code\local\Mage\Core\Block\Template.php(273): Mage_Core_Block_Template->fetchView('adminhtml\\defau...')
#25 \app\code\local\Mage\Core\Block\Template.php(287): Mage_Core_Block_Template->renderView()
#26 \app\code\core\Mage\Adminhtml\Block\Template.php(81): Mage_Core_Block_Template->_toHtml()
#27 \app\code\core\Mage\Core\Block\Abstract.php(919): Mage_Adminhtml_Block_Template->_toHtml()
#28 \app\code\community\FireGento\DynamicCategory\Model\Observer.php(53): Mage_Core_Block_Abstract->toHtml()
#29 \app\code\core\Mage\Core\Model\App.php(1358): FireGento_DynamicCategory_Model_Observer->adminhtmlCatalogCategoryTabs(Object(Varien_Event_Observer))
#30 \app\code\core\Mage\Core\Model\App.php(1337): Mage_Core_Model_App->_callObserverMethod(Object(FireGento_DynamicCategory_Model_Observer), 'adminhtmlCatalo...', Object(Varien_Event_Observer))
#31 \app\Mage.php(448): Mage_Core_Model_App->dispatchEvent('adminhtml_catal...', Array)
#32 \app\code\core\Mage\Adminhtml\Block\Catalog\Category\Tabs.php(159): Mage::dispatchEvent('adminhtml_catal...', Array)
#33 \app\code\core\Mage\Core\Block\Abstract.php(293): Mage_Adminhtml_Block_Catalog_Category_Tabs->_prepareLayout()
#34 \app\code\core\Mage\Core\Model\Layout.php(456): Mage_Core_Block_Abstract->setLayout(Object(Aoe_Layout_Model_Layout))
#35 \app\code\core\Mage\Adminhtml\Block\Catalog\Category\Edit\Form.php(55): Mage_Core_Model_Layout->createBlock('adminhtml/catal...', 'tabs')
#36 \app\code\community\Codewix\Preview\Block\Adminhtml\Catalog\Category\Edit\Form.php(37): Mage_Adminhtml_Block_Catalog_Category_Edit_Form->_prepareLayout()
#37 \app\code\core\Mage\Core\Block\Abstract.php(293): Codewix_Preview_Block_Adminhtml_Catalog_Category_Edit_Form->_prepareLayout()
#38 \app\code\core\Mage\Core\Model\Layout.php(456): Mage_Core_Block_Abstract->setLayout(Object(Aoe_Layout_Model_Layout))
#39 \app\code\core\Mage\Adminhtml\Block\Widget\Form\Container.php(93): Mage_Core_Model_Layout->createBlock('adminhtml/catal...')
#40 \app\code\core\Mage\Core\Block\Abstract.php(293): Mage_Adminhtml_Block_Widget_Form_Container->_prepareLayout()
#41 \app\code\core\Mage\Core\Model\Layout.php(456): Mage_Core_Block_Abstract->setLayout(Object(Aoe_Layout_Model_Layout))
#42 \app\code\core\Mage\Core\Model\Layout.php(472): Mage_Core_Model_Layout->createBlock('adminhtml/catal...', 'category.edit')
#43 \app\code\core\Mage\Core\Model\Layout.php(239): Mage_Core_Model_Layout->addBlock('adminhtml/catal...', 'category.edit')
#44 \app\code\local\Aoe\Layout\Model\Layout.php(76): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#45 \app\code\core\Mage\Core\Model\Layout.php(205): Aoe_Layout_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#46 \app\code\local\Aoe\Layout\Model\Layout.php(57): Mage_Core_Model_Layout->generateBlocks(Object(Mage_Core_Model_Layout_Element))
#47 \app\code\core\Mage\Core\Model\Layout.php(210): Aoe_Layout_Model_Layout->generateBlocks(Object(Mage_Core_Model_Layout_Element))
#48 \app\code\local\Aoe\Layout\Model\Layout.php(57): Mage_Core_Model_Layout->generateBlocks(NULL)
#49 \app\code\core\Mage\Core\Controller\Varien\Action.php(344): Aoe_Layout_Model_Layout->generateBlocks()
#50 \app\code\core\Mage\Core\Controller\Varien\Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#51 \app\code\core\Mage\Adminhtml\Controller\Action.php(275): Mage_Core_Controller_Varien_Action->loadLayout(NULL, true, true)
#52 \app\code\core\Mage\Adminhtml\controllers\Catalog\CategoryController.php(201): Mage_Adminhtml_Controller_Action->loadLayout()
#53 \app\code\core\Mage\Core\Controller\Varien\Action.php(418): Mage_Adminhtml_Catalog_CategoryController->editAction()
#54 \app\code\core\Mage\Core\Controller\Varien\Router\Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('edit')
#55 \app\code\core\Mage\Core\Controller\Varien\Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#56 \app\code\core\Mage\Core\Model\App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#57 \app\Mage.php(684): Mage_Core_Model_App->run(Array)
#58 \index.php(83): Mage::run('', 'store')
#59 {main}

Also i can't see the dynamic category table in the database. Someone can help me? Thanks

**Comment by danielchicote** [comment]
I have reinstalled the module via modman, and now it's working.

**Comment by danielchicote** [comment]
It was an uncompatibillity with other module (Codewix preview).
